#!/usr/bin/env python2.7
import sys
import os
def spawnDaemon():
    # do the UNIX double-fork magic, see Stevens' "Advanced 
    # Programming in the UNIX Environment" for details (ISBN 0201563177)
    try: 
        pid = os.fork()
        if pid > 0:
            return # parent process, return and keep running

    except OSError, e:
        print >>sys.stderr, "fork #1 failed: %d (%s)" % (e.errno, e.strerror) 
        sys.exit(1)

    os.setsid()
    # fork second time
    try: 
        pid = os.fork() 
        if pid > 0:
            sys.exit(0) # exit from second parent
    except OSError, e: 
        print >>sys.stderr, "fork #2 failed: %d (%s)" % (e.errno, e.strerror) 
        sys.exit(1)

    # Run code in forked enviroment... 
    project_dir = (os.path.dirname(os.path.realpath(__file__)))
    os.system(os.path.join(project_dir,"lib","grove_child.py"))
    os._exit(os.EX_OK) # Finished.

spawnDaemon()