#!/usr/bin/env python2.7
import sys
import os
def spawnDaemon():
    # do the UNIX double-fork magic, see Stevens' "Advanced 
    # Programming in the UNIX Environment" for details (ISBN 0201563177)
    try: 
        pid = os.fork()
        if pid > 0:
            # parent process, return and keep running
            return

    except OSError, e:
        print >>sys.stderr, "fork #1 failed: %d (%s)" % (e.errno, e.strerror) 
        sys.exit(1)

    os.setsid()
    # fork second time
    try: 
        pid = os.fork() 
        if pid > 0:
            # exit from second parent
            sys.exit(0) 
    except OSError, e: 
        print >>sys.stderr, "fork #2 failed: %d (%s)" % (e.errno, e.strerror) 
        sys.exit(1)

    # Run code in forked enviroment... 
    os.system("/Users/rever/Documents/customBashExecute/child")
    # Finished.
    os._exit(os.EX_OK)
spawnDaemon()